name: "Deploy MonkFocus"

on:
  push:
    tags:
      - "MonkFocus/v*"

env: 
  APP_NAME: "MonkFocus"
  APP_VERSION: ${{ github.ref }}
  PROJECT_PATH: MonkFocusApp/MonkFocusApp.csproj

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}
    
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: ${{ github.ref }}
         release_name: ${{ github.ref }}

      - name: Zip Publish Folder
        run: |
          7z a publish.zip MonkFocusApp/bin/Release/net6.0-windows/win-x64/publish/*

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          asset_path: publish.zip
          asset_name: ${{ env.APP_NAME }}.zip
          asset_content_type: application/zip
          #pattern: MonkFocusApp/bin/Release/net6.0-windows/win-x64/publish/*
          release-url: ${{ steps.create_release.outputs.upload_url }}
